name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: remessa-app:latest
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  # deployment:
  #   runs-on: 'ubuntu-latest'
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: AWS Credentials
  #       uses: aws-actions/configure-aws-credentials@v1
  #       with:
  #         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         aws-region: us-east-1
  #   - name: 'Deploy'
  #     uses: 'deliverybot/helm3@v1'
  #     with:
  #       release: 'nginx'
  #       namespace: 'default'
  #       chart: 'app'
  #       token: '${{ github.token }}'
  #       values: |
  #         name: foobar
  #     env:
  #       KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'